FROM node:20-alpine AS base

FROM base AS builder

WORKDIR /app

COPY ./dev/medusa/my-medusa-store/ .

RUN npm install
RUN npm run build

FROM base AS final

WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/.medusa/server /app
COPY --from=builder /app/package.json /app/package.json

EXPOSE 9000

CMD ["npm", "run", "docker-start"]