version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: medusa-my-medusa-store
    ports:
      - '5433:5432' # Changed the port to avoid conflicts with other services to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
